### ISSUE TITLE
Minor changes to the Readme file

### ISSUE THREAD

**Issue by Tarvone** [fedeperin/potterapi#2]
Hey there!
I think in your readme file in the Languages part the endpoint for English should be: `/en/` because `/us/` does not seem to work at all.
And I also seem to encounter a connection timeout error whenever I hit the end points with the full colon inserted before the language parameter like this -->  `/:lang/books` and it seems to work well without it, like this --> `/lang/books`

Other than that I have really enjoyed working with your API. It has helped me learn a lot and I truly appreciate the effort you have put into maintaining it. Keep up the great work!

**Comment by fedeperin** [comment]
Hi, thanks for the feedback! You are right; I'll change it. The purpose of that was to render an emoji, but depending on the device, sometimes text appears instead.  

This is how it should appear:
![image](https://github.com/fedeperin/potterapi/assets/83504427/a09b77dd-54ec-457b-a89a-df52b4ce2026)
But on some devices, it renders like this:
![image](https://github.com/fedeperin/potterapi/assets/83504427/d0e20a34-8a29-42c8-9713-c65b62dd7bed)
I'm happy you enjoyed using the API, and I really appreciate your feedback. If you have any other suggestions, please open an Issue or a Pull Request, I'm always happy to answer.

**Comment by fedeperin** [comment]
Also, the colon was there to represent that ``lang`` should be replaced with the corresponding language. I think it's more clear maybe to put it inside brackets []. I'll also apply that change.

**Comment by Tarvone** [comment]
That definitely looks better and is more understandable. Thanks for the
adjustments and again kudos for the great work.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
